# Generated by Django 3.0.5 on 2020-09-26 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 9, 26, 15, 7, 36, 458311, tzinfo=utc))),
                ('image', models.ImageField(default='default.jpg', upload_to='fires')),
                ('x_min', models.FloatField(null=True)),
                ('x_max', models.FloatField(null=True)),
                ('y_min', models.FloatField(null=True)),
                ('y_max', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThermalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xi', models.FloatField(null=True)),
                ('xa', models.FloatField(null=True)),
                ('yi', models.FloatField(null=True)),
                ('ya', models.FloatField(null=True)),
                ('fire_status', models.CharField(choices=[('EXT', 'extinguished'), ('BRN', 'burning')], default='BRN', max_length=3)),
                ('land_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.LandCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FireInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.FireObject')),
                ('fire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.FireType')),
                ('thermal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.ThermalPoint')),
            ],
        ),
    ]
