# Generated by Django 3.1.1 on 2020-09-26 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 9, 26, 10, 54, 34, 707177, tzinfo=utc))),
                ('image', models.ImageField(default='default.jpg', upload_to='fires')),
            ],
        ),
        migrations.CreateModel(
            name='FireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThermalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xi', models.FloatField()),
                ('xa', models.FloatField()),
                ('yi', models.FloatField()),
                ('ya', models.FloatField()),
                ('fire_status', models.CharField(choices=[('EXT', 'extinguished'), ('BRN', 'burning')], default='BRN', max_length=3)),
                ('land_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.landcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FireInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.fireobject')),
                ('fire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.firetype')),
                ('thermal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.thermalpoint')),
            ],
        ),
    ]
