# Generated by Django 3.0.5 on 2020-09-26 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireobject',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 15, 53, 46, 10922, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='fireobject',
            constraint=models.UniqueConstraint(fields=('x_min', 'x_max', 'y_min', 'y_max'), name='unique fire'),
        ),
    ]
