# Generated by Django 3.0.5 on 2020-09-26 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200926_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireinfo',
            name='fire_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.FireType'),
        ),
        migrations.AlterField(
            model_name='fireobject',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 17, 1, 18, 949979, tzinfo=utc)),
        ),
    ]
