# Generated by Django 3.0.5 on 2020-09-26 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20200927_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireobject',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 22, 5, 26, 396876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thermalpoint',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 22, 5, 26, 396515, tzinfo=utc)),
        ),
    ]
