# Generated by Django 3.0.5 on 2020-09-27 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200927_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalpoint',
            name='satelite_image',
            field=models.ImageField(default='default.jpg', upload_to='satelites'),
        ),
        migrations.AlterField(
            model_name='fireobject',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 1, 22, 57, 919189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thermalpoint',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 1, 22, 57, 918535, tzinfo=utc)),
        ),
    ]
