# Generated by Django 3.0.5 on 2020-09-27 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20200927_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireobject',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 3, 45, 9, 972065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thermalpoint',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 3, 45, 9, 971621, tzinfo=utc)),
        ),
    ]
