version: '3.5'

services:

  firemonitor_db:
    env_file:
      - environ/.env.dev.db
    ports:
      - 54320:5432

  firemonitor:
    command: gunicorn FireMonitoring.wsgi:application --log-level debug --access-logfile '-' --timeout 500 --bind 0.0.0.0:8000
    env_file:
      - environ/.env.dev
