version: '3.5'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - firemonitor
    networks:
      - firemonitor-internal
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  firemonitor_redis:
    container_name: firemonitor_redis
    hostname: firemonitor_redis
    image: redis:latest
    networks:
      - firemonitor-internal
    expose:
      - 6379
    restart: on-failure

  firemonitor_db:
    image: postgres:12.0-alpine
    container_name: firemonitor_db
    hostname: firemonitor_db
    env_file:
      - environ/.env.dev.db
    networks:
      - firemonitor-internal
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 54320:5432

  firemonitor:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: gunicorn FireMonitoring.wsgi:application --log-level info --timeout 500 --bind 0.0.0.0:8000
    container_name: firemonitor
    depends_on:
      - firemonitor_redis
      - firemonitor_db
    expose:
      - 8000
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
      - logs_volume:/home/backend/web/log
    hostname: firemonitor
    image: firemonitor-image
    networks:
      - firemonitor-internal
    restart: on-failure
    environment:
      - DJANGO_SETTING_MODULE=FireMonitoring.develop
    env_file:
      - environ/.env.dev

networks:
  firemonitor-internal:

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
