"""
Django settings for FireMonitoring project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from .base import *
import os
from celery.schedules import crontab
DEBUG = True
SECRET_KEY = 'r*=%h-z)t(9dn7lqz^vx-hq9sh!n&zcu-n+u_e##!%+e(tuqw0'
ALLOWED_HOSTS = ["*"]


DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.postgresql_psycopg2',
        "NAME": 'fire_database',
        "USER": 'fire_user',
        "PASSWORD": '123456',
        # "HOST": 'firemonitor_db',
        # "PORT": '5432',
        "HOST": 'localhost',
        "PORT": '54320',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CASCADE_URL = 'http://kaskad.ukmmchs.ru'

CELERY_BROKER_URL = 'redis://firemonitor_redis:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

CELERY_TIMEZONE = 'Asia/Novosibirsk'

# Celery cron tab settings
CELERY_BEAT_SCHEDULE = {
    'fetch_thermal_points_by_date_task': {
        'task': 'monitor.tasks.fetch_thermal_points',
        'schedule': crontab(minute='*/1'),
    },
}


